from __future__ import annotations

import json
from pathlib import Path
from urllib.request import Request, urlopen


APPLEDB_DEVICES_URL = "https://api.appledb.dev/device/main.json"
BASE_DIR = Path(__file__).resolve().parents[1]
OUTPUT_PATH = BASE_DIR / "device_catalog.py"
USER_AGENT = "iPhoneLabelPrinter catalog updater"


def _device_identifiers(device: dict) -> list[str]:
    identifiers = device.get("identifier") or []
    if isinstance(identifiers, str):
        identifiers = [identifiers]
    return [
        identifier.strip()
        for identifier in identifiers
        if isinstance(identifier, str)
        and (identifier.strip().startswith("iPhone") or identifier.strip().startswith("iPad"))
    ]


def _color_names(device: dict) -> tuple[str, ...]:
    colors = []
    for color in device.get("colors") or []:
        if not isinstance(color, dict):
            continue
        name = (color.get("name") or "").strip()
        if name and name not in colors:
            colors.append(name)
    return tuple(colors)


def _load_appledb_devices() -> list[dict]:
    request = Request(APPLEDB_DEVICES_URL, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=30) as response:
        payload = json.loads(response.read().decode("utf-8"))
    if not isinstance(payload, list):
        raise ValueError("AppleDB device payload is not a list.")
    return [device for device in payload if isinstance(device, dict)]


def _literal_dict(values: dict[str, object], indent: int = 4) -> str:
    lines = ["{"]
    for key in sorted(values):
        lines.append(f"{' ' * indent}{key!r}: {values[key]!r},")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    names: dict[str, str] = {}
    colors: dict[str, tuple[str, ...]] = {}

    for device in _load_appledb_devices():
        name = (device.get("name") or "").strip()
        if not name:
            continue
        color_names = _color_names(device)
        for identifier in _device_identifiers(device):
            names[identifier] = name
            if color_names:
                colors[identifier] = color_names

    content = f'''"""Generated iPhone/iPad ProductType catalog.

Generated by tools/update_device_catalog.py from AppleDB's device API.
Do not edit by hand; add overrides in model_mapping.py or variant_resolver.py.
"""

from __future__ import annotations


PRODUCT_TYPE_TO_MARKETING_NAME = {_literal_dict(names)}


PRODUCT_COLOR_OPTIONS = {_literal_dict(colors)}
'''
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} with {len(names)} model names and {len(colors)} color lists.")


if __name__ == "__main__":
    main()
